# ------------------------------------------------------- #
#      Please do not modify this autogenerated file.      #
#  Use  >> build.sh --publish << to update its content.   #
# ------------------------------------------------------- #
    
CC7_VERSION_EXT='0.7.0-beta3'
