// Generated code - DO NOT EDIT !!
// Generated by 'data-converter.sh'

#include <cc7tests/TestDirectory.h>
#include <cc7tests/TestResource.h>

namespace cc7
{
namespace tests
{
/*
  Available files:

     * test-data/json-simple.json
     * test-data/json-complex.json
     * test-data/mac-test-data.json
     * test-data/md-test-data.json

  Usage:

    #include <cc7tests/TestDirectory.h>

    namespace cc7::tests {
       extern cc7::tests::TestDirectory g_testFiles;
    }

    void someTestFunction() {
       cc7::tests::TestFile f = g_testFiles.findFile("test-data/json-simple.json");
       // Do whatever you want with TestFile object
       // You don't need to close file or directory
    }
 */

// -----------------------------------------------------------------------------
// File: test-data/json-simple.json
// -----------------------------------------------------------------------------
static const cc7::byte json_simple_json_bytes[] = {
0x7b,0x0a,0x20,0x22,0x6b,0x65,0x79,0x31,0x22,0x09,0x09,0x3a,0x20,0x22,0x76,0x61,
0x6c,0x75,0x65,0x31,0x22,0x2c,0x0a,0x20,0x22,0x74,0x72,0x75,0x65,0x22,0x3a,0x09,
0x09,0x74,0x72,0x75,0x65,0x09,0x2c,0x0a,0x20,0x22,0x66,0x61,0x6c,0x73,0x65,0x22,
0x20,0x3a,0x09,0x09,0x66,0x61,0x6c,0x73,0x65,0x2c,0x0a,0x20,0x22,0x65,0x6d,0x70,
0x74,0x79,0x22,0x09,0x3a,0x09,0x6e,0x75,0x6c,0x6c,0x2c,0x0a,0x20,0x22,0x6f,0x62,
0x6a,0x65,0x63,0x74,0x22,0x20,0x3a,0x0a,0x20,0x7b,0x0a,0x09,0x20,0x22,0x78,0x78,
0x78,0x22,0x3a,0x22,0x74,0x68,0x69,0x73,0x20,0x69,0x73,0x20,0x78,0x78,0x78,0x22,
0x20,0x2c,0x0a,0x09,0x20,0x22,0x79,0x79,0x79,0x22,0x3a,0x66,0x61,0x6c,0x73,0x65,
0x2c,0x0a,0x09,0x20,0x22,0x7a,0x7a,0x7a,0x22,0x3a,0x7b,0x0a,0x09,0x09,0x20,0x22,
0x69,0x6e,0x74,0x65,0x67,0x65,0x72,0x22,0x20,0x3a,0x0a,0x09,0x09,0x09,0x36,0x34,
0x2c,0x0a,0x09,0x09,0x20,0x22,0x64,0x6f,0x75,0x62,0x6c,0x65,0x22,0x20,0x20,0x3a,
0x0a,0x09,0x09,0x09,0x36,0x2e,0x34,0x2c,0x0a,0x09,0x09,0x20,0x22,0x75,0x6e,0x69,
0x63,0x6f,0x64,0x65,0x31,0x22,0x3a,0x22,0xc4,0xbd,0x61,0x6c,0x69,0x65,0x20,0x70,
0x6f,0xc4,0xbe,0x6e,0xc3,0xa9,0x22,0x2c,0x0a,0x09,0x09,0x20,0x22,0x75,0x6e,0x69,
0x63,0x6f,0x64,0x65,0x32,0x22,0x3a,0x22,0x5c,0x75,0x30,0x31,0x33,0x64,0x61,0x6c,
0x69,0x65,0x20,0x70,0x6f,0x5c,0x75,0x30,0x31,0x33,0x45,0x6e,0x5c,0x75,0x30,0x30,
0x45,0x39,0x22,0x0a,0x09,0x20,0x7d,0x0a,0x20,0x7d,0x2c,0x0a,0x20,0x22,0x61,0x72,
0x72,0x61,0x79,0x22,0x20,0x3a,0x0a,0x20,0x5b,0x0a,0x09,0x09,0x22,0x61,0x22,0x2c,
0x20,0x22,0x62,0x22,0x2c,0x20,0x22,0x63,0x22,0x2c,0x20,0x74,0x72,0x75,0x65,0x2c,
0x0a,0x09,0x09,0x7b,0x22,0x73,0x75,0x62,0x2d,0x61,0x72,0x72,0x61,0x79,0x22,0x3a,
0x5b,0x31,0x2c,0x32,0x2c,0x33,0x2c,0x34,0x5d,0x7d,0x2c,0x0a,0x09,0x09,0x7b,0x22,
0x73,0x75,0x62,0x2d,0x61,0x72,0x72,0x61,0x79,0x22,0x3a,0x5b,0x31,0x2e,0x31,0x2c,
0x32,0x2e,0x32,0x2c,0x33,0x2e,0x33,0x2c,0x34,0x2e,0x34,0x5d,0x7d,0x2c,0x0a,0x09,
0x09,0x7b,0x22,0x73,0x75,0x62,0x2d,0x61,0x72,0x72,0x61,0x79,0x22,0x3a,0x5b,0x2d,
0x31,0x2c,0x20,0x2d,0x31,0x2e,0x31,0x2c,0x20,0x31,0x65,0x33,0x0a,0x09,0x09,0x09,
0x09,0x09,0x20,0x20,0x2c,0x33,0x2e,0x32,0x65,0x2d,0x31,0x5d,0x0a,0x09,0x20,0x20,
0x20,0x20,0x7d,0x0a,0x20,0x20,0x5d,0x0a,0x7d,};
static const size_t json_simple_json_size = 425;
// -----------------------------------------------------------------------------
//
static cc7::tests::TestResource json_simple_json
	(
		reinterpret_cast<const cc7::byte*>(json_simple_json_bytes),
		json_simple_json_size,
		"test-data/json-simple.json"
	);
//
// -----------------------------------------------------------------------------
// File: test-data/json-complex.json
// -----------------------------------------------------------------------------
static const char json_complex_json_bytes[] = R"cc7resourcxx({
  "web-app": {
    "servlet-mapping": {
      "cofaxTools": "/tools/*", 
      "cofaxCDS": "/", 
      "fileServlet": "/static/*", 
      "cofaxAdmin": "/admin/*", 
      "cofaxEmail": "/cofaxutil/aemail/*"
    }, 
    "taglib": {
      "taglib-location": "/WEB-INF/tlds/cofax.tld", 
      "taglib-uri": "cofax.tld"
    }, 
    "servlet": [
      {
        "servlet-name": "cofaxCDS", 
        "init-param": {
          "cachePagesStore": 100, 
          "searchEngineListTemplate": "forSearchEnginesList.htm", 
          "configGlossary:adminEmail": "ksm@pobox.com", 
          "maxUrlLength": 500, 
          "dataStoreTestQuery": "SET NOCOUNT ON;select test='test';", 
          "defaultFileTemplate": "articleTemplate.htm", 
          "dataStoreLogFile": "/usr/local/tomcat/logs/datastore.log", 
          "templateLoaderClass": "org.cofax.FilesTemplateLoader", 
          "dataStoreClass": "org.cofax.SqlDataStore", 
          "redirectionClass": "org.cofax.SqlRedirection", 
          "templateOverridePath": "", 
          "cacheTemplatesStore": 50, 
          "dataStoreUrl": "jdbc:microsoft:sqlserver://LOCALHOST:1433;DatabaseName=goon", 
          "searchEngineFileTemplate": "forSearchEngines.htm", 
          "cachePagesTrack": 200, 
          "cachePackageTagsStore": 200, 
          "dataStoreName": "cofax", 
          "dataStorePassword": "dataStoreTestQuery", 
          "useJSP": false, 
          "defaultListTemplate": "listTemplate.htm", 
          "configGlossary:poweredBy": "Cofax", 
          "dataStoreUser": "sa", 
          "jspListTemplate": "listTemplate.jsp", 
          "jspFileTemplate": "articleTemplate.jsp", 
          "dataStoreMaxConns": 100, 
          "cachePagesDirtyRead": 10, 
          "cachePagesRefresh": 10, 
          "cacheTemplatesTrack": 100, 
          "dataStoreConnUsageLimit": 100, 
          "configGlossary:installationAt": "Philadelphia, PA", 
          "searchEngineRobotsDb": "WEB-INF/robots.db", 
          "templateProcessorClass": "org.cofax.WysiwygTemplate", 
          "cachePackageTagsRefresh": 60, 
          "configGlossary:staticPath": "/content/static", 
          "templatePath": "templates", 
          "useDataStore": true, 
          "cacheTemplatesRefresh": 15, 
          "dataStoreDriver": "com.microsoft.jdbc.sqlserver.SQLServerDriver", 
          "configGlossary:poweredByIcon": "/images/cofax.gif", 
          "cachePackageTagsTrack": 200, 
          "dataStoreLogLevel": "debug", 
          "dataStoreInitConns": 10
        }, 
        "servlet-class": "org.cofax.cds.CDSServlet"
      }, 
      {
        "servlet-name": "cofaxEmail", 
        "init-param": {
          "mailHostOverride": "mail2", 
          "mailHost": "mail1"
        }, 
        "servlet-class": "org.cofax.cds.EmailServlet"
      }, 
      {
        "servlet-name": "cofaxAdmin", 
        "servlet-class": "org.cofax.cds.AdminServlet"
      }, 
      {
        "servlet-name": "fileServlet", 
        "servlet-class": "org.cofax.cds.FileServlet"
      }, 
      {
        "servlet-name": "cofaxTools", 
        "init-param": {
          "logLocation": "/usr/local/tomcat/logs/CofaxTools.log", 
          "fileTransferFolder": "/usr/local/tomcat/webapps/content/fileTransferFolder", 
          "log": 1, 
          "dataLog": 1, 
          "dataLogLocation": "/usr/local/tomcat/logs/dataLog.log", 
          "adminGroupID": 4, 
          "lookInContext": 1, 
          "removePageCache": "/content/admin/remove?cache=pages&id=", 
          "removeTemplateCache": "/content/admin/remove?cache=templates&id=", 
          "logMaxSize": "", 
          "dataLogMaxSize": "", 
          "betaServer": true, 
          "templatePath": "toolstemplates/"
        }, 
        "servlet-class": "org.cofax.cms.CofaxToolsServlet"
      }
    ]
  }
}
)cc7resourcxx";
static const size_t json_complex_json_size = 3792;
// -----------------------------------------------------------------------------
//
static cc7::tests::TestResource json_complex_json
	(
		reinterpret_cast<const cc7::byte*>(json_complex_json_bytes),
		json_complex_json_size,
		"test-data/json-complex.json"
	);
//
// -----------------------------------------------------------------------------
// File: test-data/mac-test-data.json
// -----------------------------------------------------------------------------
static const char mac_test_data_json_bytes[] = R"cc7resourcxx({
    "description": "Test data for cc7/crypto/MAC algorithm",
    "data": [{
        "alg" : "KMAC-128",
        "tests": [{
            "key"    : "404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F",
            "data"   : "00010203",
            "mac"    : "e5780b0d3ea6f7d3a429c5706aa43a00fadbd7d49628839e3187243f456ee14e"
        },{
            "key"    : "404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F",
            "data"   : "00010203",
            "custom" : "My Tagged Application",
            "mac"    : "3b1fba963cd8b0b59e8c1a6d71888b7143651af8ba0a7070c0979e2811324aa5"
        },{
            "key"    : "404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F",
            "data"   : "000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBFC0C1C2C3C4C5C6C7",
            "custom" : "My Tagged Application",
            "mac"    : "1F5B4E6CCA02209E0DCB5CA635B89A15E271ECC760071DFD805FAA38F9729230"
        }]
    },{
        "alg" : "KMAC-256",
        "tests": [{
            "key"    : "404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F",
            "data"   : "00010203",
            "custom" : "My Tagged Application",
            "mac"    : "20C570C31346F703C9AC36C61C03CB64C3970D0CFC787E9B79599D273A68D2F7F69D4CC3DE9D104A351689F27CF6F5951F0103F33F4F24871024D9C27773A8DD"
        },{
            "key"    : "404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F",
            "data"   : "000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F303132333435363738393A3B3C3D3E3F404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F606162636465666768696A6B6C6D6E6F707172737475767778797A7B7C7D7E7F808182838485868788898A8B8C8D8E8F909192939495969798999A9B9C9D9E9FA0A1A2A3A4A5A6A7A8A9AAABACADAEAFB0B1B2B3B4B5B6B7B8B9BABBBCBDBEBFC0C1C2C3C4C5C6C7",
            "custom" : "",
            "mac"    : "75358CF39E41494E949707927CEE0AF20A3FF553904C86B08F21CC414BCFD691589D27CF5E15369CBBFF8B9A4C2EB17800855D0235FF635DA82533EC6B759B69"
        }]
    },{
        "alg" : "HMAC-SHA-256",
        "tests": [{
            "key"  : "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b",
            "data" : "4869205468657265",
            "mac"  : "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7"
        },{
            "key"  : "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "data" : "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
            "mac"  : "773ea91e36800e46854db8ebd09181a72959098b3ef8c122d9635514ced565fe"
        },{
            "key"  : "0102030405060708090a0b0c0d0e0f10111213141516171819",
            "data" : "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd",
            "mac"  : "82558a389a443c0ea4cc819899f2083a85f0faa3e578f8077a2e3ff46729665b"
        },{
            "key"  : "0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c",
            "data" : "546573742057697468205472756e636174696f6e",
            "mac"  : "a3b6167473100ee06e0c796c2955552b",
            "mac_size" : 16
        },{
            "key"  : "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "data" : "54657374205573696e67204c6172676572205468616e20426c6f636b2d53697a65204b6579202d2048617368204b6579204669727374",
            "mac"  : "60e431591ee0b67f0d8a26aacbf5b77f8e0bc6213728c5140546040f0ee37f54"
        },{
            "key"  : "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "data" : "5468697320697320612074657374207573696e672061206c6172676572207468616e20626c6f636b2d73697a65206b657920616e642061206c6172676572207468616e20626c6f636b2d73697a6520646174612e20546865206b6579206e6565647320746f20626520686173686564206265666f7265206265696e6720757365642062792074686520484d414320616c676f726974686d2e",
            "mac"  : "9b09ffa71b942fcb27635fbcd5b0e944bfdc63644f0713938a7f51535c3a35e2"
        }]
    },{
        "alg" : "HMAC-SHA-384",
        "tests": [{
            "key"  : "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "data" : "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
            "mac"  : "88062608d3e6ad8a0aa2ace014c8a86f0aa635d947ac9febe83ef4e55966144b2a5ab39dc13814b94e3ab6e101a34f27"
        },{
            "key"  : "0102030405060708090a0b0c0d0e0f10111213141516171819",
            "data" : "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd",
            "mac"  : "3e8a69b7783c25851933ab6290af6ca77a9981480850009cc5577c6e1f573b4e6801dd23c4a7d679ccf8a386c674cffb"
        },{
            "key"  : "0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c",
            "data" : "546573742057697468205472756e636174696f6e",
            "mac"  : "3abf34c3503b2a23a46efc619baef897",
            "mac_size" : 16
        },{
            "key"  : "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "data" : "54657374205573696e67204c6172676572205468616e20426c6f636b2d53697a65204b6579202d2048617368204b6579204669727374",
            "mac"  : "4ece084485813e9088d2c63a041bc5b44f9ef1012a2b588f3cd11f05033ac4c60c2ef6ab4030fe8296248df163f44952"
        },{
            "key"  : "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "data" : "5468697320697320612074657374207573696e672061206c6172676572207468616e20626c6f636b2d73697a65206b657920616e642061206c6172676572207468616e20626c6f636b2d73697a6520646174612e20546865206b6579206e6565647320746f20626520686173686564206265666f7265206265696e6720757365642062792074686520484d414320616c676f726974686d2e",
            "mac"  : "6617178e941f020d351e2f254e8fd32c602420feb0b8fb9adccebb82461e99c5a678cc31e799176d3860e6110c46523e"
        }]
    },{
        "alg" : "HMAC-SHA-512",
        "tests": [{
            "key"  : "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "data" : "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
            "mac"  : "fa73b0089d56a284efb0f0756c890be9b1b5dbdd8ee81a3655f83e33b2279d39bf3e848279a722c806b485a47e67c807b946a337bee8942674278859e13292fb"
        },{
            "key"  : "0102030405060708090a0b0c0d0e0f10111213141516171819",
            "data" : "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd",
            "mac"  : "b0ba465637458c6990e5a8c5f61d4af7e576d97ff94b872de76f8050361ee3dba91ca5c11aa25eb4d679275cc5788063a5f19741120c4f2de2adebeb10a298dd"
        },{
            "key"  : "0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c",
            "data" : "546573742057697468205472756e636174696f6e",
            "mac"  : "415fad6271580a531d4179bc891d87a6",
            "mac_size" : 16
        },{
            "key"  : "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "data" : "54657374205573696e67204c6172676572205468616e20426c6f636b2d53697a65204b6579202d2048617368204b6579204669727374",
            "mac"  : "80b24263c7c1a3ebb71493c1dd7be8b49b46d1f41b4aeec1121b013783f8f3526b56d037e05f2598bd0fd2215d6a1e5295e64f73f63f0aec8b915a985d786598"
        },{
            "key"  : "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "data" : "5468697320697320612074657374207573696e672061206c6172676572207468616e20626c6f636b2d73697a65206b657920616e642061206c6172676572207468616e20626c6f636b2d73697a6520646174612e20546865206b6579206e6565647320746f20626520686173686564206265666f7265206265696e6720757365642062792074686520484d414320616c676f726974686d2e",
            "mac"  : "e37b6a775dc87dbaa4dfa9f96e5e3ffddebd71f8867289865df5a32d20cdc944b6022cac3c4982b10d5eeb55c3e4de15134676fb6de0446065c97440fa8c6a58"
        }]
    },{
        "alg" : "HMAC-SHA3-256",
        "tests": [{
            "key"  : "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b",
            "data" : "4869205468657265",
            "mac"  : "ba85192310dffa96e2a3a40e69774351140bb7185e1202cdcc917589f95e16bb"
        },{
            "key"  : "4a656665",
            "data" : "7768617420646f2079612077616e7420666f72206e6f7468696e673f",
            "mac"  : "c7d4072e788877ae3596bbb0da73b887c9171f93095b294ae857fbe2645e1ba5"
        },{
            "key"  : "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "data" : "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
            "mac"  : "84ec79124a27107865cedd8bd82da9965e5ed8c37b0ac98005a7f39ed58a4207"
        },{
            "key"  : "0102030405060708090a0b0c0d0e0f10111213141516171819",
            "data" : "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd",
            "mac"  : "57366a45e2305321a4bc5aa5fe2ef8a921f6af8273d7fe7be6cfedb3f0aea6d7"
        },{
            "key"  : "0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c",
            "data" : "546573742057697468205472756e636174696f6e",
            "mac"  : "6e02c64537fb118057abb7fb66a23b3c",
            "mac_size" : 16
        }]
    },{
        "alg" : "HMAC-SHA3-384",
        "tests": [{
            "key"  : "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b",
            "data" : "4869205468657265",
            "mac"  : "68d2dcf7fd4ddd0a2240c8a437305f61fb7334cfb5d0226e1bc27dc10a2e723a20d370b47743130e26ac7e3d532886bd"
        },{
            "key"  : "4a656665",
            "data" : "7768617420646f2079612077616e7420666f72206e6f7468696e673f",
            "mac"  : "f1101f8cbf9766fd6764d2ed61903f21ca9b18f57cf3e1a23ca13508a93243ce48c045dc007f26a21b3f5e0e9df4c20a"
        },{
            "key"  : "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "data" : "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
            "mac"  : "275cd0e661bb8b151c64d288f1f782fb91a8abd56858d72babb2d476f0458373b41b6ab5bf174bec422e53fc3135ac6e"
        },{
            "key"  : "0102030405060708090a0b0c0d0e0f10111213141516171819",
            "data" : "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd",
            "mac"  : "3a5d7a879702c086bc96d1dd8aa15d9c46446b95521311c606fdc4e308f4b984da2d0f9449b3ba8425ec7fb8c31bc136"
        },{
            "key"  : "0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c",
            "data" : "546573742057697468205472756e636174696f6e",
            "mac"  : "47c51ace1ffacffd7494724682615783",
            "mac_size" : 16
        }]
    },{
        "alg" : "HMAC-SHA3-512",
        "tests": [{
            "key"  : "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b",
            "data" : "4869205468657265",
            "mac"  : "eb3fbd4b2eaab8f5c504bd3a41465aacec15770a7cabac531e482f860b5ec7ba47ccb2c6f2afce8f88d22b6dc61380f23a668fd3888bb80537c0a0b86407689e"
        },{
            "key"  : "4a656665",
            "data" : "7768617420646f2079612077616e7420666f72206e6f7468696e673f",
            "mac"  : "5a4bfeab6166427c7a3647b747292b8384537cdb89afb3bf5665e4c5e709350b287baec921fd7ca0ee7a0c31d022a95e1fc92ba9d77df883960275beb4e62024"
        },{
            "key"  : "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "data" : "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
            "mac"  : "309e99f9ec075ec6c6d475eda1180687fcf1531195802a99b5677449a8625182851cb332afb6a89c411325fbcbcd42afcb7b6e5aab7ea42c660f97fd8584bf03"
        },{
            "key"  : "0102030405060708090a0b0c0d0e0f10111213141516171819",
            "data" : "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd",
            "mac"  : "b27eab1d6e8d87461c29f7f5739dd58e98aa35f8e823ad38c5492a2088fa0281993bbfff9a0e9c6bf121ae9ec9bb09d84a5ebac817182ea974673fb133ca0d1d"
        },{
            "key"  : "0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c",
            "data" : "546573742057697468205472756e636174696f6e",
            "mac"  : "0fa7475948f43f48ca0516671e18978c",
            "mac_size" : 16
        }]
    }]
}
)cc7resourcxx";
static const size_t mac_test_data_json_size = 13613;
// -----------------------------------------------------------------------------
//
static cc7::tests::TestResource mac_test_data_json
	(
		reinterpret_cast<const cc7::byte*>(mac_test_data_json_bytes),
		mac_test_data_json_size,
		"test-data/mac-test-data.json"
	);
//
// -----------------------------------------------------------------------------
// File: test-data/md-test-data.json
// -----------------------------------------------------------------------------
static const char md_test_data_json_bytes[] = R"cc7resourcxx({
    "description": "Test data for cc7/crypto/MessageDigest algorithm",
    "data": [{
        "alg" : "SHA3-256",
        "tests": [{
            "message" : "",
            "hash"    : "a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a"
        },{
            "message" : "e9",
            "hash"    : "f0d04dd1e6cfc29a4460d521796852f25d9ef8d28b44ee91ff5b759d72c1e6d6"
        },{
            "message" : "275645b5a2514fe65a82efac57e406f224e0259677674f1d133f00a5ee9a6d1a8fed0eadbbff5a825041d2a9715d",
            "hash"    : "c70a874d786cd0f3f09fa4dc1bb8f551d45f26d77ad63de1a9fdfb3b7c09c041"
        },{
            "message" : "b1caa396771a09a1db9bc20543e988e359d47c2a616417bbca1b62cb02796a888fc6eeff5c0b5c3d5062fcb4256f6ae1782f492c1cf03610b4a1fb7b814c057878e1190b9835425c7a4a0e182ad1f91535ed2a35033a5d8c670e21c575ff43c194a58a82d4a1a44881dd61f9f8161fc6b998860cbe4975780be93b6f87980bad0a99aa2cb7556b478ca35d1f3746c33e2bb7c47af426641cc7bbb3425e2144820345e1d0ea5b7da2c3236a52906acdc3b4d34e474dd714c0c40bf006a3a1d889a632983814bbc4a14fe5f159aa89249e7c738b3b73666bac2a615a83fd21ae0a1ce7352ade7b278b587158fd2fabb217aa1fe31d0bda53272045598015a8ae4d8cec226fefa58daa05500906c4d85e7567",
            "hash"    : "cb5648a1d61c6c5bdacd96f81c9591debc3950dcf658145b8d996570ba881a05"
        }]
    },{
        "alg" : "SHA3-384",
        "tests": [{
            "message" : "",
            "hash"    : "0c63a75b845e4f7d01107d852e4c2485c51a50aaaa94fc61995e71bbee983a2ac3713831264adb47fb6bd1e058d5f004"
        },{
            "message" : "80",
            "hash"    : "7541384852e10ff10d5fb6a7213a4a6c15ccc86d8bc1068ac04f69277142944f4ee50d91fdc56553db06b2f5039c8ab7"
        },{
            "message" : "5bbc2d4efe63cbfc9fc221dd8d8384075a79c80a27d6a8c5219e677f4c5bb8338013dc2ab1770acf735d13c0bc704621ec2691350cf3ea2f53bded45ef8fc70702",
            "hash"    : "dd0bbfe4b799642191abe316df9d59a3743566778b4459c51c3be3f658bdce45516ad188fbe1a8cad8a1fa78f8ebb645"
        },{
            "message" : "5fe35923b4e0af7dd24971812a58425519850a506dfa9b0d254795be785786c319a2567cbaa5e35bcf8fe83d943e23fa5169b73adc1fcf8b607084b15e6a013df147e46256e4e803ab75c110f77848136be7d806e8b2f868c16c3a90c14463407038cb7d9285079ef162c6a45cedf9c9f066375c969b5fcbcda37f02aacff4f31cded3767570885426bebd9eca877e44674e9ae2f0c24cdd0e7e1aaf1ff2fe7f80a1c4f5078eb34cd4f06fa94a2d1eab5806ca43fd0f06c60b63d5402b95c70c21ea65a151c5cfaf8262a46be3c722264b",
            "hash"    : "3054d249f916a6039b2a9c3ebec1418791a0608a170e6d36486035e5f92635eaba98072a85373cb54e2ae3f982ce132b"
        }]
    },{
        "alg" : "SHA3-512",
        "tests": [{
            "message" : "",
            "hash"    : "a69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26"
        },{
            "message" : "e5",
            "hash"    : "150240baf95fb36f8ccb87a19a41767e7aed95125075a2b2dbba6e565e1ce8575f2b042b62e29a04e9440314a821c6224182964d8b557b16a492b3806f4c39c1"
        },{
            "message" : "23cc7f9052d5e22e6712fab88e8dfaa928b6e015ca589c3b89cb745b756ca7c7634a503bf0228e71c28ee2",
            "hash"    : "6ecf3ad6064218ee101a555d20fab6cbeb6b145b4eeb9c8c971fc7ce05581a34b3c52179590e8a134be2e88c7e549875f4ff89b96374c6995960de3a5098cced"
        },{
            "message" : "e34acd510cb32ca5f97298a3829244bb23322229fd7a07821dd40a8d01582d5558873f7c0a3d00d278e1872605dfe15dd558fbc1d518c19bfbc88803cf64a9f72af06fab3d673420d6f5c6f8df65108927ddf63066c980e77b153b1af79fdcb7dfec2785ae1a0fb69a151fbf180e1867a229dc1eb8768a912523eb7b83f00dbe01e22db2643cdabd4cab5824b9c14320cda47435d40829bf815a5fce7a3e8333183c4adb67b6de5c751e3acec966d7dc31b7881ac165a29a182361bae573873faa6146a8c07160bc9cd68d6650e41dc254c8de788777404971e4b7e7cb76610a41b9e9c07654ab04493b199357255dfbc04140f52f244af414062afe342f59bb64acfbcc9146065d04b5a5fee410dfaefd887439bf5607c58af282a72986b77b9ca243731a31b8ef56acfb4e028dea04910742ed42f4c0e25a0f8789b063c2716f038a5e18fc0ae1c688e12cb684c725062474b9bde6be730cc4014dd4aec3c667379834938f445cddb120400addbf38e449d0443a1446a1297bb79a9a4f02a10ca6359e94d2ae87218f803105801866b1dd2037c066a393389b72190c2ec72be5b9294421ad8f8b1c8ac8a8af561ad6f7482a3958c41b73c18cfa7231345a8b7ad63bcd4508318f560bc24c11450fb13df1b7f30916f8664cb5174c114702ea536735e205cbdabc567834c632363d1e0c428e0ddb4480966280914fb5500970f9d2dd2a6bded33aa43be7bd1b12ed46eba2792ed636fc2b8a542f242438b544f381fc4e7e296430c8baa3dad2bf685062793efe03d4b34d4d99ba7366e54f8fc9da59f54694d4",
            "hash"    : "a1416054e488c1e013762d642b2c63361b33e4fc528149845606de20998bf2afec05da53067477a3c27ebb3c0d24ad3dd6ed390335977f129f1b6b1526c0e0c8"
        }]
    },{
        "alg" : "SHA-256",
        "tests": [{
            "message" : "",
            "hash"    : "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        },{
            "message" : "c299209682",
            "hash"    : "f0887fe961c9cd3beab957e8222494abb969b1ce4c6557976df8b0f6d20e9166"
        },{
            "message" : "ea157c02ebaf1b22de221b53f2353936d2359d1e1c97",
            "hash"    : "9df5c16a3f580406f07d96149303d8c408869b32053b726cf3defd241e484957"
        },{
            "message" : "5f664be0c0f3d2fc9a1a7ed6b515ef9c52ad1c7fb3acf2c2de943e109f91cc12ccadd041cc4386f95ab616cf8762ba25fed322fc8c351809e00c600a8f26e25a5bcd0bc3b44170947f65b4f417b8ac769187c2ee4561978289cced04c036c37f942ec10f7fd4d7f6908e22ed6cfd0fb89330c2fde417b956643aaca53baab8a8ff38bdcd35e60547159b26618e1b29128a35ebd2733fc4adf6bf6796076b09fd2554c6a4df5e40ae97f389f986f843ad00000515f9c001aec9c4e47e2c60fea78de8a33c8423d1539dfe125c5b7ea4b17cf8d86e7f84b88264afec06b370dfcebf5e1d3e2c1f005faf248b321593964587852b830c7231504fe947d6a385f399441cfc52df3914fa55cdba25bd215f91a80fc8ffa872b34113dbbd9504868331a38c081fa659574b186169db590f48be67fe75885b6c877d37ec16ebde5ad7be6414084e88670f7b7f485efcf44599f44cbbfbc62e48f62b438319823aeb3767101ec6868e4c85b113ea623193ab9a5ae0ac226328ee4674bf0a90ff1f20eb542e110870bfee01165ab03c2240299319aa3ab1045247bf7f34e8410d96e13aae465597b42336cad2de00b67602a7cb5832cd7253b239ab752a85f452a6166e9de0523bf9c20c2a0c274396d5",
            "hash"    : "044d823532092c22a4b48181cfb2c796e1f5b98bcd713a21f70b5afcceef1d73"
        }]
    },{
        "alg" : "SHA-384",
        "tests": [{
            "message" : "",
            "hash"    : "38b060a751ac96384cd9327eb1b1e36a21fdb71114be07434c0cc7bf63f6e1da274edebfe76f65fbd51ad2f14898b95b"
        },{
            "message" : "8d45a55d5ce1f928e6",
            "hash"    : "de76683575a050e2eb5ef95ee201f82416478a1d14bf3d96d1fd4efd52b1a28fed8dfee1830070001dc102a21f761d20"
        },{
            "message" : "184215145da49db417e8bdd573d6282de073e674c3dea86b6c78591d4947f5655a9d9eb0e5f4ed046b1d8642da9aefa80448a299504160a1b000c9b4d3c62ab69b3d96",
            "hash"    : "8995cd7fc0956e124075440686beece17a6256b282e7988a0c998f790e3995c974383179893477bcc32d1f114129b496"
        },{
            "message" : "62c6a169b9be02b3d7b471a964fc0bcc72b480d26aecb2ed460b7f50016ddaf04c51218783f3aadfdff5a04ded030d7b3fb7376b61ba30b90e2da921a4470740d63fb99fa16cc8ed81abaf8ce4016e50df81da832070372c24a80890aa3a26fa675710b8fb718266249d496f313c55d0bada101f8f56eeccee4345a8f98f60a36662cfda794900d12f9414fcbdfdeb85388a814996b47e24d5c8086e7a8edcc53d299d0d033e6bb60c58b83d6e8b57f6c258d6081dd10eb942fdf8ec157ec3e75371235a8196eb9d22b1de3a2d30c2abbe0db7650cf6c7159bacbe29b3a93c92100508",
            "hash"    : "0730e184e7795575569f87030260bb8e54498e0e5d096b18285e988d245b6f3486d1f2447d5f85bcbe59d5689fc49425"
        }]
    },{
        "alg" : "SHA-512",
        "tests": [{
            "message" : "",
            "hash"    : "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e"
        },{
            "message" : "b39f71aaa8a108",
            "hash"    : "258b8efa05b4a06b1e63c7a3f925c5ef11fa03e3d47d631bf4d474983783d8c0b09449009e842fc9fa15de586c67cf8955a17d790b20f41dadf67ee8cdcdfce6"
        },{
            "message" : "e07056d4f7277bc548099577720a581eec94141d",
            "hash"    : "59f1856303ff165e2ab5683dddeb6e8ad81f15bb578579b999eb5746680f22cfec6dba741e591ca4d9e53904837701b374be74bbc0847a92179ac2b67496d807"
        },{
            "message" : "4f7a5618870945b89f194e31b1aa802c5350326dc691df58708e34b48ce666b021d7c92330a69f1832412d8ac224156c9679dfedb383d9f9e13c21035d3d0002cfdf79b97ba0223cbbc833b0ad4cdd5229f2ddbbf6b650623d6cc9623da8a17d41db8e61cfbe772b23f4872adceb81e5f403535ff5f2ed996a67535994edf12a5f1230a494c946ed500e5280b5c8a82ddff369611afe58a85272e870cbd59a1012ce8509338a368b2c5dbb3ba2adfb33d30c494acca43896dbd8b030482841374055b81812c6f00c9e2bebe2096021feb69418a272aa356cefdfd22074ae91a8d2f1ef599a481c788dbe0afd54aac39672d401ef76d9f83175d177c9b72e2f6ab1e7525533d761d8e3603f14ea538904ed142abb3ff929ed55f4c6b17a72c685c3820b93463a67338756b2b033231a4f119cbb8d35d270a97791e8622340fc02f2093f9b393ad79161eb8c5897e21f7fc4b3ddeec02b736cc3ef04641c6179e825c319f6769f59fa5966f5957e573f9df0a2b76548cedd3e2158433dcb9de63f44f9be2b63319477570e14ee504b23b07cb2737a358154277912cd779abbeb1036f459c26ab7310f43",
            "hash"    : "713d5c26de17e1440a36aab93f7cd8111cd62fd8bea5099b2b6bf93e470e1eaeab8b925c646e9e67ce01b03b33d2b500b9400e59f0ecdfb00dd7ddcd230cc837",
        }]
    }]
}
)cc7resourcxx";
static const size_t md_test_data_json_size = 9257;
// -----------------------------------------------------------------------------
//
static cc7::tests::TestResource md_test_data_json
	(
		reinterpret_cast<const cc7::byte*>(md_test_data_json_bytes),
		md_test_data_json_size,
		"test-data/md-test-data.json"
	);
//
// -----------------------------------------------------------------------------
// Directory: test-data
// -----------------------------------------------------------------------------
//
cc7::tests::TestDirectory g_testFiles({
	&json_simple_json,
	&json_complex_json,
	&mac_test_data_json,
	&md_test_data_json,
});

} // tests
} // cc7
