## -*- mode: perl; -*-

my %targets = ();

%targets = (

    #—————————————————————————————————————————————————————————————————————
    # Base setting templates
    #—————————————————————————————————————————————————————————————————————
    
    "all-base" => {
        template         => 1,
        cflags           => '-isysroot $(CROSS_SYSROOT) -fno-common $(CROSS_COMMON)',
    },
    
    #—————————————————————————————————————————————————————————————————————
    # Base cross-compiler target settings
    # - HAVE_FORK=0 for some targets lacking fork() in their SDK's.
    #—————————————————————————————————————————————————————————————————————

    "ios-base" => {
        template         => 1,
        inherit_from     => [ "all-base" ],
        cflags           => add('-mios-version-min=$(CROSS_MIN_VERSION)'),
    },

    "tvos-base" => {
        template         => 1,
        inherit_from     => [ "all-base" ],
        cflags           => add('-mtvos-version-min=$(CROSS_MIN_VERSION)'),
        defines          => [ "HAVE_FORK=0" ],
    },

    "macos-base" => {
        inherit_from     => [ "all-base" ],
        template         => 1,
        cflags           => add('-mmacosx-version-min=$(CROSS_MIN_VERSION)'),
    },
	
    #—————————————————————————————————————————————————————————————————————
    # iOS
    #—————————————————————————————————————————————————————————————————————

    # iPhone/iPad simulator.
    "ios-sim-cross-x86_64" => {
        inherit_from     => [ "darwin64-x86_64", "ios-base" ],
    },
	
    # iPhone/iPad simulator on Apple Silicon.
    "ios-sim-cross-arm64" => {
        inherit_from     => [ "darwin64-arm64", "ios-base" ],
		cflags           => add('-target $(CROSS_TARGET)'),
    },
		
    # iOS Arm64 architecture.
    "ios64-cross-arm64" => {
        inherit_from     => [ "darwin64-arm64", "ios-base" ],
    },

    #—————————————————————————————————————————————————————————————————————
    # macOS Catalyst
    #—————————————————————————————————————————————————————————————————————

    # macOS Catalyst x86_64
    "mac-catalyst-x86_64" => {
        inherit_from     => [ "darwin64-x86_64", "macos-base" ],
        cflags           => add('-target $(CROSS_TARGET)'),
    },
	
	# macOS Catalyst arm64
    "mac-catalyst-arm64" => {
        inherit_from     => [ "darwin64-arm64", "macos-base" ],
        cflags           => add('-target $(CROSS_TARGET)'),
    },


    #—————————————————————————————————————————————————————————————————————
    # tvOS
    #—————————————————————————————————————————————————————————————————————

    ## Apple TV simulator (x86_64)
    "tvos-sim-cross-x86_64" => {
        inherit_from     => [ "darwin64-x86_64", "tvos-base" ],
    },
	
    ## Apple TV simulator (Apple Silicon)
    "tvos-sim-cross-arm64" => {
        inherit_from     => [ "darwin64-arm64", "tvos-base" ],
		cflags           => add('-target $(CROSS_TARGET)'),
    },

    ## Apple TV from Apple TV 4 onward.
    "tvos64-cross-arm64" => {
        inherit_from     => [ "darwin64-arm64", "tvos-base" ],
    },

    #—————————————————————————————————————————————————————————————————————
    # macOS
    #—————————————————————————————————————————————————————————————————————

    ## Apple macOS (x86_64)
    "macos64-x86_64" => {
        inherit_from     => [ "darwin64-x86_64", "macos-base" ],
    },
	
	## Apple macOS (Apple Silicon)
	"macos64-arm64" => {
        inherit_from     => [ "darwin64-arm64", "macos-base" ],
	    cflags           => add("-mmacosx-version-min=11.0")
	}
);
